# Generated by Django 5.0.13 on 2026-01-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product name or review title', max_length=200)),
                ('price_php', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(choices=[('S', 'S-Tier'), ('A', 'A-Tier'), ('B', 'B-Tier'), ('C', 'C-Tier'), ('D', 'D-Tier'), ('F', 'F-Tier')], default='B', help_text='Overall rating of the product', max_length=1)),
                ('category', models.CharField(choices=[('AUDIO', 'Audio'), ('PERIPHERAL', 'Peripheral'), ('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('GADGET', 'Gadget')], default='AUDIO', help_text='Type of tech product', max_length=20)),
                ('specs', models.JSONField(default=dict, help_text='Product specifications as JSON. Example: {"impedance": "32", "driver": "50mm"}')),
                ('cover_image', models.ImageField(blank=True, help_text='Product cover image', null=True, upload_to='poorguy/covers/')),
                ('verdict', models.TextField(help_text='The TL;DR summary - what you should know')),
                ('content', models.TextField(help_text='Full review body with detailed analysis')),
                ('is_wishlist', models.BooleanField(default=False, help_text='Is this item on your wishlist?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tech Review',
                'verbose_name_plural': 'Tech Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
