# Generated by Django 5.0.13 on 2026-01-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorguy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE poorguy_review ADD COLUMN price_php DECIMAL(10,2) NOT NULL DEFAULT 0.00;"
        ),
    ]
