# Generated by Django 5.0.13 on 2026-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorguy', '0002_auto_20260106_1447'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Ensure price_php column exists and is properly configured
            PRAGMA foreign_keys=off;
            
            -- Create a temporary table with the correct schema
            CREATE TABLE poorguy_review_temp (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title VARCHAR(200) NOT NULL,
                price_php DECIMAL(10, 2) NOT NULL,
                grade VARCHAR(1) NOT NULL,
                category VARCHAR(20) NOT NULL,
                specs TEXT NOT NULL,
                cover_image VARCHAR(100),
                verdict TEXT NOT NULL,
                content TEXT NOT NULL,
                is_wishlist BOOLEAN NOT NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            
            -- Copy data from old table to new table
            INSERT INTO poorguy_review_temp (id, title, price_php, grade, category, specs, cover_image, verdict, content, is_wishlist, created_at, updated_at)
            SELECT id, title, COALESCE(price_php, 0.00), grade, category, specs, cover_image, verdict, content, is_wishlist, created_at, updated_at
            FROM poorguy_review;
            
            -- Drop old table and rename new table
            DROP TABLE poorguy_review;
            ALTER TABLE poorguy_review_temp RENAME TO poorguy_review;
            
            -- Recreate indexes
            CREATE INDEX poorguy_review_created_at_1000c02f ON poorguy_review (created_at);
            
            PRAGMA foreign_keys=on;
            """
        ),
    ]
